import Config

# Load .env file if it exists (keeps secrets out of git)
if File.exists?(".env") do
  File.stream!(".env")
  |> Enum.each(fn line ->
    line = String.trim(line)

    case String.split(line, "=", parts: 2) do
      [key, value] when key != "" ->
        key = String.trim(key)
        value = String.trim(value) |> String.trim("\"") |> String.trim("'")

        if not String.starts_with?(key, "#") do
          System.put_env(key, value)
        end

      _ ->
        :ok
    end
  end)
end

# Configure your database
if database_url = System.get_env("DATABASE_URL") do
  config :bidirectional_translations, BidirectionalTranslations.Repo,
    url: database_url,
    ssl: true,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 2
else
  config :bidirectional_translations, BidirectionalTranslations.Repo,
    username: "wikipedia",
    password: "wikipedia",
    hostname: "localhost",
    port: 5435,
    database: "bidirectional_translations_dev",
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :bidirectional_translations, BidirectionalTranslationsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "uCdPTg6+k5UHRf2eBO6yPz8nDp3/gV60Wj7N+hzHxVlPZ46oc3gadSdvc3ftOjzA",
  watchers: [
    esbuild:
      {Esbuild, :install_and_run, [:bidirectional_translations, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:bidirectional_translations, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :bidirectional_translations, BidirectionalTranslationsWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/bidirectional_translations_web/router\.ex$",
      ~r"lib/bidirectional_translations_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :bidirectional_translations, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Use Resend if API key is set, otherwise fall back to local adapter
if api_key = System.get_env("RESEND_API_KEY") do
  config :swoosh, :api_client, Swoosh.ApiClient.Req
  config :bidirectional_translations, BidirectionalTranslations.Mailer,
    adapter: BidirectionalTranslations.Mailer.RateLimitedAdapter,
    inner_adapter: Swoosh.Adapters.Resend,
    api_key: api_key
else
  config :swoosh, :api_client, false
end
